spring:
  profiles:
    active: local
    
  application:
    name: ecommerce
    
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        jdbc:
          batch_size: 20
          
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.sql
    
  messages:
    encoding: UTF-8
    
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
    endpoint:
      health:
        show-details: when-authorized

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: 86400000

---
spring:
  config:
    activate:
      on-profile: local
      
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres1234
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: ecommerce-local-pool
      
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
logging:
  level:
    com.example.ecommerce: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: docker
      
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres1234
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      pool-name: ecommerce-docker-pool
      
  jpa:
    show-sql: false
    
logging:
  level:
    com.example.ecommerce: INFO
    org.springframework.security: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    
  h2:
    console:
      enabled: false
      
  liquibase:
    enabled: false
    
  main:
    allow-bean-definition-overriding: true
    
app:
  jwt:
    secret: testSecretKey123456789012345678901234567890
    expiration: 3600000

logging:
  level:
    com.example.ecommerce: WARN
    org.springframework: WARN
    org.hibernate: WARN
    root: WARN